import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './styles.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Bitcount+Prop+Double:wght@100..900&family=Exile&display=swap" rel="stylesheet"></link>
      </head> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <h1> My name is Rohit Kumar Malav </h1> */}
        {children}
      </body>
    </html>
  );
}
